<div class="jumbotron">
    <h1>Bem vindo ao <span class="zf-green">ZF2-PHPBol</span></h1>
    <p>Módulo do Zend Framework 2 para geração de Boletos/Bloquetos de cobrança 
        dos principais banco brasileiros. Este projeto é baseado no <a href="https://github.com/rafaelgou/PHPBol" >PHPBol</a>
    </p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/adaoex/zf2-phpbol" target="_blank">Fork ZF2-PHPBol no GitHub &raquo;</a></p>
    <h3>Projeto contém:</h3>
    <ul>
        <li><a href="https://github.com/adoex/zf2-phpbol">ZF2-PHPBol</a></li>
        <li><a href="https://github.com/zendframework/ZendSkeletonApplication">Zend Skeleton Application</a></li>
        <li><a href="https://github.com/sebastianbergmann/phpunit">PHPUnit</a></li>
    </ul>
</div>
